# 生产环境的差异配置
spring:
  shardingsphere:
    datasource:
      master:
        url: jdbc:mysql://192.168.232.101:3306/mojito?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      slave:
        url: jdbc:mysql://192.168.232.101:13306/mojito?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

  redis:
    host: 192.168.232.101

file:
  temp-path: /opt/app/Mojito/OSS/temp/
  path: /opt/app/Mojito/OSS/

message:
  send: true

knife4j:
  production: true  # 生成环境屏蔽文档资源